"use client";

import React from "react";
import CategoryCatalog from "@/components/CategoryCatalog";
import { Sparkles, UserCheck, ShieldCheck } from "lucide-react";

export default function WallPendantLightsPage() {
  const products = [
    {
      id: "wp-1",
      title: "Amber Glass Halo Wall Sconce",
      code: "AL-WP-8001",
      material: "Amber Glass & Brushed Brass",
      dimensions: "Ø 10\" x H 14\"",
      price: "₹8,500",
      image: "/assets/Wall & Pendant Lights/Amber Glass Halo Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-2",
      title: "Amber Textured Glass Disc Wall Sconce",
      code: "AL-WP-8002",
      material: "Textured Amber Glass Disc",
      dimensions: "Ø 12\" Disc",
      price: "₹9,200",
      image: "/assets/Wall & Pendant Lights/Amber Textured Glass Disc Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-3",
      title: "Antique Layered Ring Wall Light",
      code: "AL-WP-8003",
      material: "Layered Antique Brass Rings",
      dimensions: "H 16\" x W 8\"",
      price: "₹7,800",
      image: "/assets/Wall & Pendant Lights/Antique Layered Ring Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-4",
      title: "Clear Glass Floral Disc Wall Light",
      code: "AL-WP-8004",
      material: "Handcrafted Floral Glass Disc",
      dimensions: "Ø 14\" Disc",
      price: "₹10,500",
      image: "/assets/Wall & Pendant Lights/Clear Glass Floral Disc Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-5",
      title: "Clustered Textured Glass Bud Pendant",
      code: "AL-WP-8005",
      material: "Textured Glass Buds & Gold Cables",
      dimensions: "3-Light Cluster",
      price: "₹18,500",
      image: "/assets/Wall & Pendant Lights/Clustered Textured Glass Bud Pendant Light.webp",
      subCat: "pendants",
    },
    {
      id: "wp-6",
      title: "Crystal Crown LED Wall Sconce",
      code: "AL-WP-8006",
      material: "Crown Faceted Crystals & Gold",
      dimensions: "H 12\" x W 6\"",
      price: "₹6,900",
      image: "/assets/Wall & Pendant Lights/Crystal Crown LED Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-7",
      title: "Crystal Crown Half-Drum Wall Light",
      code: "AL-WP-8007",
      material: "Half-Drum Crystal Shield",
      dimensions: "H 14\" x W 8\"",
      price: "₹8,200",
      image: "/assets/Wall & Pendant Lights/Crystal Crown Half-Drum Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-8",
      title: "Crystal Globe Disc Wall Sconce",
      code: "AL-WP-8008",
      material: "Crystal Globe & Brass Disc Backer",
      dimensions: "Ø 10\" x Depth 6\"",
      price: "₹9,800",
      image: "/assets/Wall & Pendant Lights/Crystal Globe Disc Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-9",
      title: "Crystal Hourglass Double-Globe Light",
      code: "AL-WP-8009",
      material: "Hourglass Crystal & Dual Orbs",
      dimensions: "H 18\" x W 6\"",
      price: "₹11,500",
      image: "/assets/Wall & Pendant Lights/Crystal Hourglass Double-Globe Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-10",
      title: "Double Alabaster Stone Disc Wall Light",
      code: "AL-WP-8010",
      material: "Natural Spanish Alabaster & Brass",
      dimensions: "H 20\" x W 8\"",
      price: "₹14,900",
      image: "/assets/Wall & Pendant Lights/Double Alabaster Stone Disc Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-11",
      title: "Double Crystal Disc Loop Wall Light",
      code: "AL-WP-8011",
      material: "Loop Gold Steel & Dual Crystal Discs",
      dimensions: "H 22\" x W 7\"",
      price: "₹12,800",
      image: "/assets/Wall & Pendant Lights/Double Crystal Disc Loop Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-12",
      title: "Double Opal Disc Loop Wall Sconce",
      code: "AL-WP-8012",
      material: "Frosted Opal Discs & Minimal Loop",
      dimensions: "H 18\" x W 6\"",
      price: "₹7,900",
      image: "/assets/Wall & Pendant Lights/Double Opal Disc Loop Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-13",
      title: "Double Orb LED Wall Sconce",
      code: "AL-WP-8013",
      material: "Twin Milk Glass Globes & Brass Arm",
      dimensions: "H 16\" x W 10\"",
      price: "₹9,500",
      image: "/assets/Wall & Pendant Lights/Double Orb LED Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-14",
      title: "Four-Disc Crystal Sunburst Wall Light",
      code: "AL-WP-8014",
      material: "4-Disc Crystal Cluster & Gold Radiance",
      dimensions: "Ø 18\" Sunburst",
      price: "₹13,200",
      image: "/assets/Wall & Pendant Lights/Four-Disc Crystal Sunburst Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-15",
      title: "Golden Faceted Sunburst Wall Light",
      code: "AL-WP-8015",
      material: "Faceted Gold Rays & LED Core",
      dimensions: "Ø 16\" Sunburst",
      price: "₹11,800",
      image: "/assets/Wall & Pendant Lights/Golden Faceted Sunburst Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-16",
      title: "Golden Flame Leaf LED Wall Sconce",
      code: "AL-WP-8016",
      material: "Sculpted Flame Leaf & Warm LED",
      dimensions: "H 20\" x W 5\"",
      price: "₹8,800",
      image: "/assets/Wall & Pendant Lights/Golden Flame Leaf LED Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-17",
      title: "Hanging Crystal Drum Wall Sconce",
      code: "AL-WP-8017",
      material: "Suspended Crystal Drum & Gold Bracket",
      dimensions: "H 16\" x Drop 12\"",
      price: "₹10,200",
      image: "/assets/Wall & Pendant Lights/Hanging Crystal Drum Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-18",
      title: "Hanging Crystal Orb Wall Light",
      code: "AL-WP-8018",
      material: "Crystal Orb Pendant & Wall Bracket",
      dimensions: "H 18\" x Drop 10\"",
      price: "₹9,400",
      image: "/assets/Wall & Pendant Lights/Hanging Crystal Orb Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-19",
      title: "Round Wooden Cage Bowl Pendant Light",
      code: "AL-WP-8019",
      material: "Natural Wood Slats & Black Canopy",
      dimensions: "Ø 14\" Bowl",
      price: "₹6,800",
      image: "/assets/Wall & Pendant Lights/Round Wooden Cage Bowl Pendant Light.webp",
      subCat: "pendants",
    },
    {
      id: "wp-20",
      title: "Wooden Lantern Cage Pendant Light",
      code: "AL-WP-8020",
      material: "Artisanal Wooden Lantern & Cord",
      dimensions: "Ø 12\" x H 16\"",
      price: "₹7,500",
      image: "/assets/Wall & Pendant Lights/Wooden Lantern Cage Pendant Light.webp",
      subCat: "pendants",
    },
    {
      id: "wp-21",
      title: "Single Crystal Halo Ring Pendant Light",
      code: "AL-WP-8021",
      material: "Single Crystal Ring & Slim Cord",
      dimensions: "Ø 12\" Ring",
      price: "₹8,900",
      image: "/assets/Wall & Pendant Lights/Single Crystal Halo Ring Pendant Light.webp",
      subCat: "pendants",
    },
    {
      id: "wp-22",
      title: "Ripple Ring Crystal LED Ceiling Light",
      code: "AL-WP-8022",
      material: "Ripple Faceted Crystal Ring",
      dimensions: "Ø 16\" Flush",
      price: "₹11,000",
      image: "/assets/Wall & Pendant Lights/Ripple Ring Crystal LED Ceiling Light.webp",
      subCat: "ceiling",
    },
  ];

  return (
    <CategoryCatalog
      categorySlug="wall-pendant-lights"
      title="Wall & Pendant Lights"
      tagline="Accent lighting for bedside, dining islands and corridors."
      description="Artisanal hand-blown glass pendants, crystal sconces and brushed champagne gold wall luminaires with warm anti-glare illumination."
      heroImage="/assets/Wall & Pendant Lights/Amber Glass Halo Wall Sconce.webp"
      badges={[
        { icon: Sparkles, text: "Hand-Blown Glass & Crystals" },
        { icon: UserCheck, text: "Adjustable Drop Cables" },
        { icon: ShieldCheck, text: "3-Year Warranty" },
      ]}
      subCategories={[
        { id: "all", label: "All Wall & Pendants" },
        { id: "pendants", label: "Island Pendants" },
        { id: "wall-sconces", label: "Wall Sconces" },
        { id: "ceiling", label: "Accent Ceiling Lights" },
      ]}
      products={products}
    />
  );
}
