"use client";

import React from "react";
import CategoryCatalog from "@/components/CategoryCatalog";
import { Sparkles, UserCheck, ShieldCheck } from "lucide-react";

export default function WallPendantLightsPage() {
  const products = [
    {
      id: "wp-1",
      title: "Amber Glass Halo Wall Sconce",
      code: "AL-WP-8001",
      material: "Amber Glass & Brushed Brass",
      dimensions: "Ø 10\" x H 14\"",
      image: "/assets/Wall & Pendant Lights/Amber Glass Halo Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-2",
      title: "Amber Textured Glass Disc Wall Sconce",
      code: "AL-WP-8002",
      material: "Textured Amber Glass Disc",
      dimensions: "Ø 12\" Disc",
      image: "/assets/Wall & Pendant Lights/Amber Textured Glass Disc Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-3",
      title: "Antique Layered Ring Wall Light",
      code: "AL-WP-8003",
      material: "Layered Antique Brass Rings",
      dimensions: "H 16\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Antique Layered Ring Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-4",
      title: "Clear Glass Floral Disc Wall Light",
      code: "AL-WP-8004",
      material: "Handcrafted Floral Glass Disc",
      dimensions: "Ø 14\" Disc",
      image: "/assets/Wall & Pendant Lights/Clear Glass Floral Disc Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-5",
      title: "Clustered Textured Glass Bud Pendant Light",
      code: "AL-WP-8005",
      material: "Textured Glass Buds & Gold Cables",
      dimensions: "3-Light Cluster",
      image: "/assets/Wall & Pendant Lights/Clustered Textured Glass Bud Pendant Light.webp",
      subCat: "pendants",
    },
    {
      id: "wp-6",
      title: "Crystal Crown LED Wall Sconce",
      code: "AL-WP-8006",
      material: "Crown Faceted Crystals & Gold",
      dimensions: "H 12\" x W 6\"",
      image: "/assets/Wall & Pendant Lights/Crystal Crown LED Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-7",
      title: "Crystal Crown Half-Drum Wall Light",
      code: "AL-WP-8007",
      material: "Half-Drum Crystal Shield",
      dimensions: "H 14\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Crystal Crown Half-Drum Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-8",
      title: "Crystal Globe Disc Wall Sconce",
      code: "AL-WP-8008",
      material: "Crystal Globe & Brass Disc Backer",
      dimensions: "Ø 10\" x Depth 6\"",
      image: "/assets/Wall & Pendant Lights/Crystal Globe Disc Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-9",
      title: "Crystal Hourglass Double-Globe Wall Light",
      code: "AL-WP-8009",
      material: "Hourglass Crystal & Dual Orbs",
      dimensions: "H 18\" x W 6\"",
      image: "/assets/Wall & Pendant Lights/Crystal Hourglass Double-Globe Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-10",
      title: "Double Alabaster Stone Disc Wall Light",
      code: "AL-WP-8010",
      material: "Natural Alabaster & Warm Gold",
      dimensions: "Ø 12\" x H 16\"",
      image: "/assets/Wall & Pendant Lights/Double Alabaster Stone Disc Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-11",
      title: "Double Crystal Disc Loop Wall Light",
      code: "AL-WP-8011",
      material: "Dual Faceted Crystal Discs",
      dimensions: "H 16\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Double Crystal Disc Loop Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-12",
      title: "Double Opal Disc Loop Wall Sconce",
      code: "AL-WP-8012",
      material: "Frosted Opal Discs & Brass Arm",
      dimensions: "H 14\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Double Opal Disc Loop Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-13",
      title: "Double Orb LED Wall Sconce",
      code: "AL-WP-8013",
      material: "Dual Luminous Glass Spheres",
      dimensions: "H 18\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Double Orb LED Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-14",
      title: "Double Textured Glass Disc Wall Light",
      code: "AL-WP-8014",
      material: "Fluid Ripple Glass Discs",
      dimensions: "Ø 14\" x Depth 4\"",
      image: "/assets/Wall & Pendant Lights/Double Textured Glass Disc Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-15",
      title: "Four-Disc Crystal Sunburst Wall Light",
      code: "AL-WP-8015",
      material: "Quartet Crystal Sunburst Discs",
      dimensions: "W 16\" x H 16\"",
      image: "/assets/Wall & Pendant Lights/Four-Disc Crystal Sunburst Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-16",
      title: "Four-Flower Frosted Glass Wall Light",
      code: "AL-WP-8016",
      material: "Blossoming Glass Flowers",
      dimensions: "W 14\" x H 14\"",
      image: "/assets/Wall & Pendant Lights/Four-Flower Frosted Glass Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-17",
      title: "Golden Faceted Sunburst Wall Light",
      code: "AL-WP-8017",
      material: "Faceted Gold Ray Plate",
      dimensions: "Ø 14\" Sunburst",
      image: "/assets/Wall & Pendant Lights/Golden Faceted Sunburst Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-18",
      title: "Golden Flame Leaf LED Wall Sconce",
      code: "AL-WP-8018",
      material: "Cast Gold Flame Leaf",
      dimensions: "H 20\" x W 6\"",
      image: "/assets/Wall & Pendant Lights/Golden Flame Leaf LED Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-19",
      title: "Golden Honeycomb Disc Wall Light",
      code: "AL-WP-8019",
      material: "Perforated Honeycomb Brass",
      dimensions: "Ø 12\" Disc",
      image: "/assets/Wall & Pendant Lights/Golden Honeycomb Disc Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-20",
      title: "Hanging Crystal Drum Wall Sconce",
      code: "AL-WP-8020",
      material: "Suspended Crystal Drum",
      dimensions: "H 16\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Hanging Crystal Drum Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-21",
      title: "Hanging Crystal Flower Wall Sconce",
      code: "AL-WP-8021",
      material: "Crystal Flower Pendant & Arm",
      dimensions: "H 18\" x W 6\"",
      image: "/assets/Wall & Pendant Lights/Hanging Crystal Flower Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-22",
      title: "Hanging Crystal Orb Wall Light",
      code: "AL-WP-8022",
      material: "Suspended Crystal Sphere",
      dimensions: "H 16\" x W 7\"",
      image: "/assets/Wall & Pendant Lights/Hanging Crystal Orb Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-23",
      title: "Hanging Crystal Petal Flower Wall Sconce",
      code: "AL-WP-8023",
      material: "Petal Faceted Crystals",
      dimensions: "H 18\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Hanging Crystal Petal Flower Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-24",
      title: "Oval Frame Textured Glass Disc Wall Light",
      code: "AL-WP-8024",
      material: "Gold Oval Frame & Glass Disc",
      dimensions: "H 18\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Oval Frame Textured Glass Disc Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-25",
      title: "Ribbed Glass Dome Wall Sconce",
      code: "AL-WP-8025",
      material: "Fluted Glass Dome Shade",
      dimensions: "Ø 8\" x H 10\"",
      image: "/assets/Wall & Pendant Lights/Ribbed Glass Dome Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-26",
      title: "Round Wooden Cage Bowl Pendant Light",
      code: "AL-WP-8026",
      material: "Crafted Wood Ribs & Bulb",
      dimensions: "Ø 14\" Bowl",
      image: "/assets/Wall & Pendant Lights/Round Wooden Cage Bowl Pendant Light.webp",
      subCat: "pendants",
    },
    {
      id: "wp-27",
      title: "Single Crystal Halo Ring Pendant Light",
      code: "AL-WP-8027",
      material: "Floating Crystal Ring Shade",
      dimensions: "Ø 10\" Halo",
      image: "/assets/Wall & Pendant Lights/Single Crystal Halo Ring Pendant Light.webp",
      subCat: "pendants",
    },
    {
      id: "wp-28",
      title: "Single Glass Disc Brass Wall Light",
      code: "AL-WP-8028",
      material: "Minimalist Brass & Glass Plate",
      dimensions: "Ø 10\" Disc",
      image: "/assets/Wall & Pendant Lights/Single Glass Disc Brass Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-29",
      title: "Spiral Crystal Flower Wall Light",
      code: "AL-WP-8029",
      material: "Spiral Curved Crystal Blooms",
      dimensions: "H 18\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Spiral Crystal Flower Wall Light.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-30",
      title: "Three-Tier Crystal Column Wall Sconce",
      code: "AL-WP-8030",
      material: "Triple Layered Crystal Prism",
      dimensions: "H 20\" x W 7\"",
      image: "/assets/Wall & Pendant Lights/Three-Tier Crystal Column Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-31",
      title: "Twin Crystal Cone Wall Sconce",
      code: "AL-WP-8031",
      material: "Dual Cone Crystals & Gold Bracket",
      dimensions: "H 16\" x W 8\"",
      image: "/assets/Wall & Pendant Lights/Twin Crystal Cone Wall Sconce.webp",
      subCat: "wall-sconces",
    },
    {
      id: "wp-32",
      title: "Wooden Lantern Cage Pendant Light",
      code: "AL-WP-8032",
      material: "Rustic Wooden Lantern Frame",
      dimensions: "H 14\" x W 10\"",
      image: "/assets/Wall & Pendant Lights/Wooden Lantern Cage Pendant Light.webp",
      subCat: "pendants",
    },
  ];

  return (
    <CategoryCatalog
      categorySlug="wall-pendant-lights"
      title="Wall & Pendant Lights"
      tagline="Artisanal glass, blown pendants and ambient wall sconces."
      description="Elevate your bedside, dining nook, corridor or feature wall with hand-blown glass island pendants and solid brass sconces."
      heroImage="/banner/Wall & Pendant Lights.webp"
      badges={[
        { icon: Sparkles, text: "Handblown Glass" },
        { icon: UserCheck, text: "Solid Brass Fitting" },
        { icon: ShieldCheck, text: "3-Year Warranty" },
      ]}
      subCategories={[
        { id: "all", label: "All Wall & Pendants" },
        { id: "wall-sconces", label: "Wall Sconces" },
        { id: "pendants", label: "Pendant Lights" },
      ]}
      products={products}
    />
  );
}
